version: 2
updates:
  - package-ecosystem: "npm"
    directory: "gurubu-backend/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "gurubu-client/"
    schedule:
      interval: "weekly"
